//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace movilton_mvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class articulos
    {
        public int id_articulo { get; set; }
        public string titulo { get; set; }
        public string descripcion { get; set; }
        public string imagen { get; set; }
        public string ubicacion { get; set; }
        public int id_user { get; set; }
    
        public virtual usuarios usuarios { get; set; }
    }
}
