//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace movilton_mvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class perfil_empresa
    {
        public string rut_empresa { get; set; }
        public string nombre_empresa { get; set; }
        public string direccion { get; set; }
        public string email { get; set; }
        public string logo { get; set; }
        public string representante { get; set; }
        public string slogan { get; set; }
        public int telefono { get; set; }
        public int id_user { get; set; }
    
        public virtual usuarios usuarios { get; set; }
    }
}
